spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${CLIENTID}
            client-secret: ${CLIENTSECRET}
            scope: openid, profile, email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          google:
            issuer-uri: https://accounts.google.com